Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2021-12, with the labels that each got.

#3 Ignore build folder for prettier and editorconfig
  .editorconfig
  .prettierignore
Labels: size/XS

#2 Create React App
  .gitignore
  Dockerfile
  build-n-publish.sh
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/index.css
  src/index.tsx
  src/logo.svg
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  tsconfig.json
  yarn.lock
Labels: size/L

#4 Some documentation
  README.md
  demo/demo.html
Labels: size/M

#13 Prettier & EditorConfig inconsistency
  .prettierrc
  demo/demo.html
  public/index.html
  src/index.css
Labels: size/S

#14 Renaming editors-ufe as editors-webapp
  Jenkinsfile
  build-n-publish.sh
  cdn-helpers/upload.sh
  demo/demo.html
Labels: size/XS

#5 Joy with routes
  package.json
  src/App.test.tsx
  src/App.tsx
  src/Main.css
  src/Main.test.tsx
  src/Main.tsx
  src/index.tsx
  src/routes/expenses.tsx
  src/routes/invoices.tsx
  yarn.lock
Labels: size/L

#17 chore: fix package name
  package.json
Labels: size/XS

#21 Avoid default exports
  src/App.test.tsx
  src/App.tsx
  src/Main.test.tsx
  src/Main.tsx
  src/index.tsx
  src/reportWebVitals.ts
  src/routes/expenses.tsx
  src/routes/invoices.tsx
Labels: size/M

#26 [DE-416] Add unlayer editor
  .env.development
  .gitignore
  package.json
  src/App.tsx
  src/Main.css
  src/Main.test.tsx
  src/Main.tsx
  src/components/Editor.tsx
  src/external/merge.tags.js
  src/index.css
  src/routes/campaigns.tsx
  src/routes/templates.tsx
  yarn.lock
Labels: size/L

#28 Minor adjustments
  .editorconfig
  .prettierignore
  src/components/App.test.tsx
  src/components/App.tsx
  src/components/Editor.tsx
  src/components/Main.css
  src/components/Main.test.tsx
  src/components/Main.tsx
  src/components/campaigns.tsx
  src/components/expenses.tsx
  src/components/invoices.tsx
  src/components/logo.svg
  src/components/templates.tsx
  src/external/merge.tags.js
  src/index.tsx
Labels: size/M

#22 App architecture
  README.md
  demo/index.html
  docs/architecture.svg
  docs/resolve-app-services.png
  docs/store-app-services.png
  public/index.html
  src/abstractions/app-configuration-renderer/index.ts
  src/abstractions/configuration.ts
  src/abstractions/index.ts
  src/abstractions/services.ts
  src/components/App.tsx
  src/components/AppServicesContext.test.tsx
  src/components/AppServicesContext.tsx
  src/components/ConfigurationDemo.tsx
  src/composition-root.test.ts
  src/composition-root.ts
  src/default-configuration.ts
  src/implementations/SingletonLazyAppServicesContainer.test.ts
  src/implementations/SingletonLazyAppServicesContainer.ts
  src/implementations/app-configuration-renderer/index.ts
  src/index.tsx
Labels: size/XL

#30 fix: fix how the old basename configuration is being read
  src/index.tsx
Labels: size/S

#29 DE-415 - User Session
  src/abstractions/app-session/app-session-state-accessor.ts
  src/abstractions/app-session/app-session-state-monitor.ts
  src/abstractions/app-session/app-session-state.ts
  src/abstractions/app-session/index.ts
  src/abstractions/common/result-types.ts
  src/abstractions/configuration.ts
  src/abstractions/doppler-legacy-client/index.ts
  src/abstractions/services.ts
  src/components/App.tsx
  src/components/AppSessionStateContext.tsx
  src/components/NavigateToExternalUrl.tsx
  src/components/RequireAuth.test.tsx
  src/components/RequireAuth.tsx
  src/components/SessionDemo.tsx
  src/composition-root.ts
  src/default-configuration.ts
  src/implementations/SingletonLazyAppServicesContainer.ts
  src/implementations/app-session/pulling-app-session-state-monitor.ts
  src/implementations/dummies/doppler-legacy-client.tsx
  src/index.tsx
  src/utils/index.ts
Labels: size/L

#33 Unlayer types improvements
  src/components/Editor.tsx
Labels: size/S

#34 refactor: read unlayer projectId from configuration
  src/abstractions/configuration.ts
  src/components/Editor.tsx
  src/default-configuration.ts
Labels: size/L

#35 fix: read unlayer user data from session
  src/components/Editor.tsx
  src/implementations/dummies/doppler-legacy-client.tsx
Labels: size/S

#36 DE-426 - Clean-up
  .env.development
  src/default-configuration.ts
Labels: size/XS

#37 [DE-424] loading Unlayer customJS with the loader
  src/abstractions/configuration.ts
  src/components/Editor.tsx
  src/default-configuration.ts
Labels: size/S

#38 chore: remove reading of a deprecated configuration entry
  src/index.tsx
Labels: size/XS

#39 Redirect back after login
  src/components/RequireAuth.test.tsx
  src/components/RequireAuth.tsx
Labels: size/M

#40 Inject dependencies hook
  README.md
  docs/resolve-app-services.png
  src/components/AppServicesContext.test.tsx
  src/components/AppServicesContext.tsx
  src/components/ConfigurationDemo.tsx
  src/components/Editor.tsx
  src/components/NavigateToExternalUrl.tsx
  src/components/RequireAuth.tsx
  src/components/SessionDemo.tsx
Labels: size/L
