Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2022-03, with the labels that each got.

#124 [DE-486] Agregado componentes header y footer para uso del editor de campañas
  public/index.html
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/PortalComponent.tsx
Labels: size/M

#119 De-486 layout editor
  package.json
  src/components/App.test.tsx
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/components/Editor.tsx
  src/components/EditorBottomBar.css
  src/components/EditorBottomBar.tsx
  src/components/EditorTopBar.css
  src/components/EditorTopBar.tsx
  src/components/Main.css
  src/components/Main.test.tsx
  src/components/Main.tsx
  src/index.css
  src/index.tsx
Labels: size/L

#126 Change VS Code IDE color
  .vscode/settings.json
Labels: size/S

#127 Use EmailEditor.onReady in place of onLoad
  src/components/Editor.tsx
Labels: size/XS

#125 [DE-502] actualización de pruebas unitarias
  src/components/Campaign.test.tsx
  src/components/Footer.test.tsx
  src/components/Header.test.tsx
  src/components/PortalComponent.test.tsx
  src/utils/testUtils.tsx
Labels: size/L

#131 feat: add markup for app header
  src/components/EditorTopBar.css
  src/components/EditorTopBar.tsx
Labels: size/M

#133 fix: add markups with links for the menu
  src/components/EditorTopBar.tsx
Labels: size/S

#145 [DE-526] Corregir error en la carga del contenido
  package.json
  src/components/Editor.tsx
  yarn.lock
Labels: size/XS

#136 [DE-525] Update exit menu behaviour
  package.json
  src/abstractions/configuration.ts
  src/components/DropdownButton.tsx
  src/components/EditorTopBar.test.tsx
  src/components/EditorTopBar.tsx
  src/default-configuration.ts
  yarn.lock
Labels: size/L
