Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2022-05, with the labels that each got.

#214 [DE-582] Add campaign auto save
  package.json
  src/components/SingletonEditor.tsx
  yarn.lock
Labels: size/S

#215 Minor fixes
  package.json
  src/components/SingletonEditor.test.tsx
  src/components/SingletonEditor.tsx
  yarn.lock
Labels: size/S

#217 Fix has changes flag
  src/components/SingletonEditor.tsx
Labels: size/XS

#216 DE-561 - generate thumbnail
  src/abstractions/domain/content.ts
  src/components/SingletonEditor.test.tsx
  src/components/SingletonEditor.tsx
  src/implementations/HtmlEditorApiClientImpl.test.ts
  src/implementations/HtmlEditorApiClientImpl.ts
  src/implementations/dummies/html-editor-api-client.tsx
  src/utils/index.ts
Labels: size/L
