Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2022-01, with the labels that each got.

#46 chore: remove wrong email field from unlayerUser
  src/abstractions/app-session/app-session-state.ts
  src/abstractions/doppler-legacy-client/index.ts
  src/components/Editor.tsx
  src/implementations/dummies/doppler-legacy-client.tsx
Labels: size/XS

#44 chore: allow to parse version and nocache from querystring in demo page
  demo/index.html
Labels: size/M

#45 Fix useEffect dependency
  Dockerfile
  src/components/AppSessionStateContext.tsx
Labels: size/XS

#49 Rename components
  src/components/App.tsx
  src/components/Campaign.tsx
  src/components/Template.tsx
  src/components/campaigns.tsx
  src/components/templates.tsx
Labels: size/S

#48 [DE-425] Implementes client for doppler legacy
  package.json
  src/abstractions/configuration.ts
  src/abstractions/services.ts
  src/composition-root.ts
  src/default-configuration.ts
  src/implementations/DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/SingletonLazyAppServicesContainer.ts
  yarn.lock
Labels: size/L

#47 fix: use onLoad handler in place of useEffect for loading editor design
  src/__mocks__/react-email-editor.tsx
  src/components/Editor.test.tsx
  src/components/Editor.tsx
Labels: size/L

#51 Session data
  src/abstractions/app-session/app-session-state.ts
  src/abstractions/doppler-legacy-client/index.ts
  src/implementations/DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/app-session/pulling-app-session-state-monitor.ts
  src/implementations/dummies/doppler-legacy-client.tsx
Labels: size/M

#52 chore: remove redundant code in DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.test.ts
Labels: size/XS

#54 DE-430 - Allow dummy behavior
  demo/index.html
  src/abstractions/configuration.ts
  src/composition-root.ts
  src/default-configuration.ts
Labels: size/S

#53 fix: support loading design in a existent EmailEditor
  src/components/Campaign.tsx
  src/components/Editor.tsx
  src/components/Template.tsx
Labels: size/S

#50 DE-399 - Get dummy campaign content
  src/abstractions/html-editor-api-client/index.ts
  src/abstractions/services.ts
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/composition-root.ts
  src/implementations/SingletonLazyAppServicesContainer.ts
  src/implementations/dummies/html-editor-api-client.tsx
  src/implementations/dummies/sample-unlayer-design.json
Labels: size/L

#57 fix: fix the structure of doppler legacy user data
  src/abstractions/doppler-legacy-client/index.ts
  src/implementations/DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/dummies/doppler-legacy-client.tsx
Labels: size/M

#58 DE-399 - Implement HTML Editor API client
  src/abstractions/configuration.ts
  src/composition-root.ts
  src/default-configuration.ts
  src/implementations/HtmlEditorApiClientImpl.test.ts
  src/implementations/HtmlEditorApiClientImpl.ts
Labels: size/L

#60 fix: render campaign unexpected error as string
  src/components/Campaign.tsx
Labels: size/XS

#72 Updates
  package.json
  yarn.lock
Labels: size/S

#70 Menu
  src/components/App.test.tsx
  src/components/Main.test.tsx
  src/components/Main.tsx
Labels: size/L

#71 refactor: improve result representation types
  src/abstractions/common/result-types.ts
  src/abstractions/doppler-legacy-client/index.ts
  src/abstractions/html-editor-api-client/index.ts
  src/components/Campaign.tsx
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/HtmlEditorApiClientImpl.ts
  src/implementations/dummies/doppler-legacy-client.tsx
  src/implementations/dummies/html-editor-api-client.tsx
Labels: size/L

#74 Unload design from Editor when it is not defined
  src/components/Campaign.tsx
  src/components/Editor.tsx
  src/components/Template.tsx
Labels: size/S

#75 fix: unload design on un-mounting editor component
  src/components/Editor.tsx
Labels: size/S

#76 fix: update HTML Editor API client to the new schema
  src/implementations/HtmlEditorApiClientImpl.test.ts
  src/implementations/HtmlEditorApiClientImpl.ts
Labels: size/S
