Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2022-04, with the labels that each got.

#149 [DE-506] Set tools dock to left
  src/components/Editor.tsx
Labels: size/XS

#150 Remove GitLint for building INT branch
  Jenkinsfile
Labels: size/XS

#153 Refactor and fix session management
  src/abstractions/app-session/app-session-state-accessor.ts
  src/abstractions/app-session/app-session-state-monitor.ts
  src/components/App.test.tsx
  src/components/AppSessionStateContext.tsx
  src/components/Campaign.test.tsx
  src/components/Editor.test.tsx
  src/components/Main.test.tsx
  src/components/SessionDemo.tsx
  src/components/SingletonEditor.test.tsx
  src/composition-root.ts
  src/implementations/DopplerRestApiClientImpl.test.ts
  src/implementations/DopplerRestApiClientImpl.ts
  src/implementations/HtmlEditorApiClientImpl.test.ts
  src/implementations/HtmlEditorApiClientImpl.ts
  src/implementations/app-session/polling-app-session-state-monitor.ts
  src/index.tsx
  src/queries/user-fields-queries.tsx
Labels: size/L

#155 [DOM-297] Changes in tag id elements
  src/abstractions/configuration.ts
  src/default-configuration.ts
  src/index.tsx
Labels: size/XS

#151 Consume Doppler Session Micro-Frontend
  src/abstractions/doppler-legacy-client/index.ts
  src/abstractions/services.ts
  src/composition-root.ts
  src/implementations/DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/SingletonLazyAppServicesContainer.ts
  src/implementations/app-session/doppler-mfe-app-session-state-monitor.ts
  src/implementations/app-session/polling-app-session-state-monitor.ts
  src/implementations/dummies/doppler-legacy-client.tsx
Labels: size/L

#159 fix(local): fix doppler session behavior in local environment
  demo/index.html
  demo/start-demo.sh
  public/index.html
Labels: size/L

#157 [DE-508] Add multi language support
  package.json
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/components/EditorBottomBar.tsx
  src/components/EditorTopBar.test.tsx
  src/components/EditorTopBar.tsx
  src/components/i18n/DopplerIntlProvider.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/i18n/utils.tsx
  src/index.tsx
  yarn.lock
Labels: size/L

#158 DE-541 - Test language provider
  src/components/Campaign.test.tsx
  src/components/EditorTopBar.test.tsx
  src/components/i18n/TestDopplerIntlProvider.tsx
Labels: size/M

#156 [DE-539] obtener sesión desde la información de usuario
  src/abstractions/app-session/app-session-state.ts
  src/components/AppServicesContext.test.tsx
  src/components/AppSessionStateContext.test.tsx
  src/components/AppSessionStateContext.tsx
  src/components/Editor.test.tsx
  src/components/RequireAuth.test.tsx
  src/implementations/app-session/doppler-mfe-app-session-state-monitor.ts
Labels: size/L

#162 [DE-508] Update tests
  src/components/i18n/DopplerIntlProvider.test.tsx
  src/components/i18n/DopplerIntlProvider.tsx
  src/components/i18n/TranslationFiles.test.tsx
  src/components/i18n/utils.tsx
Labels: size/M

#163 [DE-545] Use the language from user session state
  src/abstractions/app-session/app-session-state.ts
  src/components/AppSessionStateContext.tsx
  src/components/i18n/DopplerIntlProvider.test.tsx
  src/components/i18n/DopplerIntlProvider.tsx
  src/implementations/app-session/doppler-mfe-app-session-state-monitor.ts
  src/index.tsx
Labels: size/L

#168 [DE-540] agregado parámetro Lang para cambiar de lenguaje
  src/components/Campaign.test.tsx
  src/components/i18n/DopplerIntlProvider.test.tsx
  src/components/i18n/DopplerIntlProvider.tsx
Labels: size/M

#169 [DE-509] Add locale to Unlayer based on user session language
  src/components/App.test.tsx
  src/components/Editor.test.tsx
  src/components/Editor.tsx
  src/components/Main.test.tsx
  src/components/SingletonEditor.test.tsx
Labels: size/M

#175 fix: add arrow dropdown
  src/components/DropdownButton.tsx
Labels: size/XS

#172 React v18 upgrade
  package.json
  src/index.tsx
  yarn.lock
Labels: size/S

#182 DE-570 - initialize Unlayer Editor extensions
  src/components/Editor.tsx
Labels: size/S

#184 fix: revert Merge pull request #172 from FromDoppler/react-v18-upgrade and other updates
  package.json
  src/index.tsx
  yarn.lock
Labels: size/M

#185 React v18 upgrade again
  package.json
  src/index.tsx
  yarn.lock
Labels: size/M

#186 [DE-566] Add click behaviour to bottom bar next button
  src/components/Campaign.tsx
  src/components/EditorBottomBar.test.tsx
  src/components/EditorBottomBar.tsx
Labels: size/M

#192 Debug with VS Code
  .vscode/launch.json
  src/components/Campaign.test.tsx
  src/components/EditorTopBar.test.tsx
  src/components/SingletonEditor.test.tsx
Labels: size/M

#195 [DE-565] Exit button bottom bar
  src/components/Campaign.tsx
  src/components/EditorBottomBar.test.tsx
  src/components/EditorBottomBar.tsx
Labels: size/M

#205 chore: update yarn test command
  package.json
Labels: size/XS

#188 [DE-580] Refactorizar hook useSingletonEditor
  src/components/Campaign.tsx
  src/components/SingletonEditor.test.tsx
  src/components/SingletonEditor.tsx
Labels: size/L

#209 [DE-505] Update links based on idABTest parameter
  src/components/Campaign.tsx
Labels: size/S

#208 [DE-576] Guardar contenido cuando se abandona el editor
  src/components/Campaign.tsx
  src/components/Editor.tsx
  src/components/SingletonEditor.test.tsx
  src/components/SingletonEditor.tsx
Labels: size/L
