Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2022-06, with the labels that each got.

#239 [DE-629] arreglada sincronización entre el auto guardado y el guardado manual del usuario
  src/components/SingletonEditor.tsx
Labels: size/S

#247 [DE-583] habilitar pruebas comentadas por error con el uso de portal
  src/components/Campaign.test.tsx
  src/components/SingletonEditor.tsx
Labels: size/M

#250 [DE-583] Usando nombres adecuados en las utilidades de pruebas para React Portal
  src/components/Campaign.test.tsx
  src/utils/testPortalUtils.tsx
  src/utils/testUtils.tsx
Labels: size/M

#258 [DE-583] agregando test para el footer en campaña
  src/components/Campaign.test.tsx
  src/utils/testPortalUtils.tsx
Labels: size/L

#262 Dependencies 2022-06-14 A
  package.json
  yarn.lock
Labels: size/XS

#264 chore: set 600px with in the dummy unlayer content
  src/implementations/dummies/sample-unlayer-design.json
Labels: size/XS

#265 fix: exit button should point to campaign drafts
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
Labels: size/M

#278 Css small change that affects menu-mfe layout
  src/components/Main.css
Labels: size/XS
