Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2022-02, with the labels that each got.

#77 Refactor unexpected errors
  src/abstractions/common/result-types.ts
  src/abstractions/doppler-legacy-client/index.ts
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/implementations/DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/HtmlEditorApiClientImpl.test.ts
  src/implementations/HtmlEditorApiClientImpl.ts
  src/implementations/dummies/doppler-legacy-client.tsx
Labels: size/L

#84 Minor refactoring
  src/components/Campaign.tsx
  src/components/Main.tsx
  src/components/SingletonEditor.test.tsx
  src/components/SingletonEditor.tsx
Labels: size/S

#86 chore: better data for demo in Dummy HtmlEditorApiClient
  src/implementations/dummies/html-editor-api-client.tsx
Labels: size/XS

#88 Remove unnecessary validation of campaign ID
  src/components/Campaign.tsx
Labels: size/S

#81 [DE-394] Agregado método para guardar html
  src/components/Campaign.tsx
  src/components/Main.tsx
  src/components/SingletonEditor.test.tsx
  src/components/SingletonEditor.tsx
Labels: size/S

#82 React Query
  package.json
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/index.tsx
  src/queries/campaign-content-queries.tsx
  yarn.lock
Labels: size/L

#87 Save model using API
  src/abstractions/html-editor-api-client/index.ts
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/implementations/HtmlEditorApiClientImpl.ts
  src/implementations/dummies/html-editor-api-client.tsx
  src/queries/campaign-content-queries.tsx
Labels: size/L

#85 Encapsulate SingletonEditor code
  src/components/Campaign.test.tsx
  src/components/Main.tsx
  src/components/SingletonEditor.test.tsx
  src/components/SingletonEditor.tsx
Labels: size/L

#90 [DE-448] corregida petición de actualización para el contenido de las campañas
  src/implementations/HtmlEditorApiClientImpl.ts
Labels: size/XS

#89 refactor: replace getDesign and getHtml by getUnlayerData
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/components/SingletonEditor.tsx
Labels: size/M

#94 Fix editor re-rendering
  src/components/AppSessionStateContext.tsx
  src/components/Editor.test.tsx
  src/components/Editor.tsx
  src/components/RequireAuth.test.tsx
  src/components/RequireAuth.tsx
  src/components/SessionDemo.tsx
Labels: size/L

#93 DE-451 - User fields
  src/abstractions/doppler-rest-api-client/index.ts
  src/abstractions/services.ts
  src/components/App.test.tsx
  src/components/Campaign.test.tsx
  src/components/Editor.test.tsx
  src/components/Editor.tsx
  src/components/Main.test.tsx
  src/components/SingletonEditor.test.tsx
  src/composition-root.ts
  src/external/merge.tags.js
  src/implementations/SingletonLazyAppServicesContainer.ts
  src/implementations/dummies/doppler-rest-api-client.tsx
  src/implementations/dummies/sample-user-fields.json
  src/queries/user-fields-queries.tsx
Labels: size/L

#97 DE-451 - Query real backend for fields
  src/abstractions/configuration.ts
  src/composition-root.ts
  src/default-configuration.ts
  src/implementations/DopplerRestApiClientImpl.test.ts
  src/implementations/DopplerRestApiClientImpl.ts
Labels: size/L

#96 refactor: move SingletonEditorProvider usage to index.tsx
  src/components/Main.tsx
  src/index.tsx
Labels: size/S

#100 DE-450 - Preparation refactoring
  src/abstractions/domain/content.ts
  src/abstractions/html-editor-api-client/index.ts
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/components/SingletonEditor.test.tsx
  src/components/SingletonEditor.tsx
  src/implementations/HtmlEditorApiClientImpl.test.ts
  src/implementations/HtmlEditorApiClientImpl.ts
  src/implementations/dummies/html-editor-api-client.tsx
  src/queries/campaign-content-queries.tsx
Labels: size/L

#101 DE-450 - Classic mode
  src/abstractions/domain/content.ts
  src/components/Main.tsx
  src/components/SingletonEditor.tsx
  src/implementations/HtmlEditorApiClientImpl.test.ts
  src/implementations/HtmlEditorApiClientImpl.ts
  src/implementations/dummies/html-editor-api-client.tsx
Labels: size/L

#104 WIP - [DE-462] Add doppler style guide using loader
  public/index.html
Labels: size/S

#105 Add the property canonicalVersion to generated asset-manifest.json
  cdn-helpers/prepare.sh
Labels: size/S

#107 Remove Preheader Text from the editor
  src/components/Editor.tsx
Labels: size/S
