Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2022-11, with the labels that each got.

#343 DE-870 - Load and show template (not saving yet)
  src/abstractions/domain/content.ts
  src/abstractions/html-editor-api-client/index.ts
  src/components/SingletonEditor.test.tsx
  src/components/SingletonEditor.tsx
  src/components/Template.test.tsx
  src/components/Template.tsx
  src/implementations/HtmlEditorApiClientImpl.test.ts
  src/implementations/HtmlEditorApiClientImpl.ts
  src/implementations/dummies/html-editor-api-client.tsx
  src/queries/campaign-content-queries.tsx
  src/queries/template-queries.tsx
Labels: size/XL

#344 DE-870 - Save template
  src/abstractions/html-editor-api-client/index.ts
  src/components/Campaign.test.tsx
  src/components/Template.test.tsx
  src/components/Template.tsx
  src/implementations/HtmlEditorApiClientImpl.test.ts
  src/implementations/HtmlEditorApiClientImpl.ts
  src/implementations/dummies/html-editor-api-client.tsx
  src/queries/template-queries.tsx
Labels: size/L

#351 [DE-895] Update button tool icon
  src/abstractions/configuration.ts
  src/components/Editor.tsx
  src/default-configuration.ts
Labels: size/S

#352 build: fix gitlint
  gitlint.sh
Labels: size/XS

#353 fix(deps): upgrade to React-Query v4 final
  package.json
  src/components/App.test.tsx
  src/components/Campaign.test.tsx
  src/components/Editor.test.tsx
  src/components/Main.test.tsx
  src/components/SingletonEditor.test.tsx
  src/components/Template.test.tsx
  src/index.tsx
  src/queries/campaign-content-queries.tsx
  src/queries/template-queries.tsx
  src/queries/user-fields-queries.tsx
  yarn.lock
Labels: size/S

#354 [DE-896] Added button back and next in the template editor
  src/components/Template.tsx
Labels: size/S
