Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2023-11, with the labels that each got.

#789 DOP-1471 Product gallery content store panel
  cspell-project-words.txt
  src/abstractions/domain/DopplerEditorSettings.ts
  src/abstractions/doppler-legacy-client/index.ts
  src/components/UnlayerEditorWrapper.test.tsx
  src/components/base-gallery/SidePanel.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/product-gallery/ProductGalleryUI.test.tsx
  src/components/product-gallery/ProductGalleryUI.tsx
  src/components/product-gallery/product-gallery-behavior.test.tsx
  src/components/product-gallery/product-gallery-behavior.ts
  src/implementations/DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/dummies/doppler-legacy-client.tsx
  src/queries/products-gallery-queries.tsx
Labels: size/L

#790 feat: handle 'continuation' without concerning its internal meaning
  src/implementations/DopplerLegacyClientImpl.ts
Labels: size/S

#795 DOP-1399 - Product gallery content store refact
  src/abstractions/doppler-legacy-client/index.ts
  src/components/base-gallery/SidePanel.tsx
  src/components/product-gallery/ProductGalleryUI.test.tsx
  src/components/product-gallery/ProductGalleryUI.tsx
  src/components/product-gallery/product-gallery-behavior.test.tsx
  src/components/product-gallery/product-gallery-behavior.ts
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/dummies/doppler-legacy-client.tsx
  src/queries/products-gallery-queries.tsx
Labels: size/L

#798 DOP-1399 - Add dynamic criteria sorting by eComerce
  src/abstractions/domain/DopplerEditorSettings.ts
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/product-gallery/HeaderSortProductsDropdown.test.tsx
  src/components/product-gallery/HeaderSortProductsDropdown.tsx
  src/components/product-gallery/ProductGalleryModal.test.tsx
  src/components/product-gallery/ProductGalleryUI.test.tsx
  src/components/product-gallery/ProductGalleryUI.tsx
  src/components/product-gallery/product-gallery-behavior.test.tsx
  src/implementations/DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/dummies/doppler-legacy-client.tsx
  src/queries/products-gallery-queries.tsx
Labels: size/L

#807 DOP-1399 - Update product gallery view
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/product-gallery/ContentRowList.tsx
  src/components/product-gallery/ProductGalleryUI.tsx
  src/implementations/dummies/doppler-legacy-client.tsx
Labels: size/L

#810 DOP-1399 - Product gallery hide dropdown
  src/components/base-gallery/SidePanel.tsx
  src/components/product-gallery/HeaderSortProductsDropdown.tsx
Labels: size/XS
