Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2023-02, with the labels that each got.

#412 [DE-869] Exporting current content design
  src/components/Campaign.tsx
  src/components/SingletonEditor.tsx
Labels: size/M

#422 [DE-869] Add test for export content as template
  src/components/Campaign.test.tsx
  src/components/SaveAsTemplateModal.test.tsx
  src/components/Template.test.tsx
Labels: size/L

#425 Fix: Request to create template from content
  src/implementations/HtmlEditorApiClientImpl.ts
Labels: size/S

#426 [DE-947] Save content when exit the editor
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/components/EditorBottomBar.test.tsx
  src/components/EditorBottomBar.tsx
  src/components/Template.test.tsx
  src/components/Template.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/smart-urls.tsx
Labels: size/L

#433 Add cspell
  Dockerfile
  cspell-project-words.txt
  cspell.json
  package.json
  src/components/PortalComponent.test.tsx
  src/components/PortalComponent.tsx
  src/components/SetCampaignContentFromTemplate.test.tsx
  src/components/continuation-urls.test.tsx
  yarn.lock
Labels: size/L

#431 [DE-808] Show message when the content is saving
  src/components/Campaign.tsx
  src/components/EditorBottomBar.css
  src/components/SavingMessage.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
Labels: size/S

#437 [DE-808] Saving label position
  src/components/EditorBottomBar.css
Labels: size/XS
