Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2023-06, with the labels that each got.

#580 DOP-1346 - Submit form
  src/components/custom-media-library/CustomMediaLibrary.test.tsx
  src/components/custom-media-library/CustomMediaLibrary.tsx
  src/components/custom-media-library/Footer.test.tsx
  src/components/custom-media-library/Footer.tsx
Labels: size/L

#582 Improve tests
  src/components/App.test.tsx
  src/components/CreateTemplateFromTemplate.test.tsx
  src/components/Main.test.tsx
  src/components/SetCampaignContentFromTemplate.test.tsx
  src/components/UnlayerEditorWrapper.test.tsx
  src/components/custom-media-library/CustomMediaLibraryModal.test.tsx
  src/components/custom-media-library/useCustomMediaLibraryBehavior.test.tsx
  src/components/singleton-editor/SingletonEditorProvider.test.tsx
Labels: size/L

#583 Image gallery queries
  src/components/custom-media-library/useCustomMediaLibraryBehavior.tsx
  src/queries/image-galleries-queries.tsx
  src/queries/image-gallery-queries.tsx
Labels: size/M

#587 DOP-1366 - Fix custom media gallery layout
  src/components/custom-media-library/CustomMediaLibrary.tsx
Labels: size/XS

#590 Minor cleanup
  src/components/custom-media-library/CustomMediaLibraryModal.test.tsx
  src/components/custom-media-library/useCustomMediaLibraryBehavior.test.tsx
  src/components/custom-media-library/useCustomMediaLibraryBehavior.tsx
  src/implementations/dummies/doppler-legacy-client.tsx
  src/queries/image-gallery-queries.tsx
  src/utils/index.test.ts
Labels: size/M

#592 Select image with double click
  src/components/custom-media-library/CustomMediaLibrary.test.tsx
  src/components/custom-media-library/CustomMediaLibrary.tsx
  src/components/custom-media-library/List.tsx
Labels: size/M

#595 Fix axios/jest interaction error in Windows
  package.json
Labels: size/XS

#596 DOP-1369 - Update content custom media library
  src/components/custom-media-library/CustomMediaLibrary.test.tsx
  src/components/custom-media-library/CustomMediaLibraryModal.test.tsx
  src/components/custom-media-library/Footer.tsx
  src/components/custom-media-library/List.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
Labels: size/L

#594 DOP-1363 - Search images
  src/abstractions/doppler-legacy-client/index.ts
  src/components/custom-media-library/CustomMediaLibrary.test.tsx
  src/components/custom-media-library/CustomMediaLibrary.tsx
  src/components/custom-media-library/CustomMediaLibraryModal.test.tsx
  src/components/custom-media-library/Header.tsx
  src/components/custom-media-library/useCustomMediaLibraryBehavior.test.tsx
  src/components/custom-media-library/useCustomMediaLibraryBehavior.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/implementations/DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/dummies/doppler-legacy-client.tsx
  src/queries/image-gallery-queries.tsx
  src/utils/index.ts
Labels: size/L

#597 DOP-1346 - loading
  src/components/custom-media-library/CustomMediaLibrary.tsx
  src/components/custom-media-library/CustomMediaLibraryModal.test.tsx
  src/components/custom-media-library/List.tsx
  src/components/custom-media-library/Loading.tsx
  src/components/custom-media-library/useCustomMediaLibraryBehavior.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
Labels: size/S

#599 Avoid double request after upload file
  src/queries/image-gallery-queries.tsx
Labels: size/XS

#606 Use URLSearchParams to create the query-string in media gallery
  src/implementations/DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.ts
Labels: size/S

#610 test: fix missing properties in test setup
  src/components/custom-media-library/CustomMediaLibrary.test.tsx
Labels: size/XS

#605 DOP-1365 - Sort images
  cspell-project-words.txt
  src/abstractions/doppler-legacy-client/index.ts
  src/components/custom-media-library/CustomMediaLibrary.tsx
  src/components/custom-media-library/Header.tsx
  src/components/custom-media-library/SortDropdown.test.tsx
  src/components/custom-media-library/SortDropdown.tsx
  src/components/custom-media-library/useCustomMediaLibraryBehavior.test.tsx
  src/components/custom-media-library/useCustomMediaLibraryBehavior.tsx
  src/components/dp-components/Dropdown.tsx
  src/components/dp-components/FieldGroup.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/implementations/DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/dummies/doppler-legacy-client.tsx
  src/queries/image-gallery-queries.tsx
Labels: size/XL

#611 Fix missing properties in test setup
  src/components/custom-media-library/CustomMediaLibrary.test.tsx
Labels: size/XS

#613 Quick and dirty fix to allw saving when thumbnail generation does not work
  src/components/singleton-editor/useSaving.test.tsx
  src/components/singleton-editor/useSaving.ts
Labels: size/M

#615 Enable the custom media gallery by default
  src/components/Campaign.test.tsx
  src/components/Template.test.tsx
  src/components/singleton-editor/SingletonEditorProvider.test.tsx
  src/components/singleton-editor/useSingletonEditor.ts
Labels: size/XS

#619 fix: accept .gif images
  src/components/custom-media-library/Footer.tsx
Labels: size/XS

#620 fix(dp-components): do not add classNames when undefined
  src/components/dp-components/FieldGroup.tsx
Labels: size/XS

#622 Refactor media gallery
  src/components/custom-media-library/Content.tsx
  src/components/custom-media-library/ContentList.tsx
  src/components/custom-media-library/ContentLoading.tsx
  src/components/custom-media-library/CustomMediaLibrary.tsx
  src/components/custom-media-library/CustomMediaLibraryModal.tsx
  src/components/custom-media-library/Footer.tsx
  src/components/custom-media-library/FooterSubmitButton.tsx
  src/components/custom-media-library/FooterUploadButton.tsx
  src/components/custom-media-library/Form.tsx
  src/components/custom-media-library/Header.tsx
  src/components/custom-media-library/HeaderSearchInput.tsx
  src/components/custom-media-library/HeaderSortDropdown.test.tsx
  src/components/custom-media-library/HeaderSortDropdown.tsx
  src/components/custom-media-library/LibraryUI.test.tsx
  src/components/custom-media-library/LibraryUI.tsx
  src/components/custom-media-library/List.tsx
  src/components/custom-media-library/SortDropdown.tsx
  src/components/custom-media-library/behavior.test.tsx
  src/components/custom-media-library/behavior.tsx
Labels: size/XL

#612 DOP-1375 - Message when there are no results
  cspell-project-words.txt
  src/components/custom-media-library/Content.tsx
  src/components/custom-media-library/ContentEmpty.tsx
  src/components/custom-media-library/ContentNoResult.tsx
  src/components/custom-media-library/LibraryUI.test.tsx
  src/components/custom-media-library/LibraryUI.tsx
  src/components/custom-media-library/behavior.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
Labels: size/M

#617 DOP-1367 - Delete selected images
  src/abstractions/doppler-legacy-client/index.ts
  src/components/custom-media-library/DeleteConfirmationModal.tsx
  src/components/custom-media-library/HeaderDeleteButton.tsx
  src/components/custom-media-library/LibraryUI.test.tsx
  src/components/custom-media-library/LibraryUI.tsx
  src/components/custom-media-library/behavior.test.tsx
  src/components/custom-media-library/behavior.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/implementations/DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/dummies/doppler-legacy-client.tsx
  src/queries/image-gallery-queries.tsx
Labels: size/XL

#628 Typesafe translations
  cspell-project-words.txt
  src/abstractions/i18n.ts
  src/components/i18n/DopplerIntlProvider.test.tsx
  src/components/i18n/DopplerIntlProvider.tsx
  src/components/i18n/TestDopplerIntlProvider.tsx
  src/components/i18n/TranslationFiles.test.tsx
  src/components/i18n/en.tsx
  src/components/i18n/setup.ts
  src/components/i18n/utils.tsx
Labels: size/L

#629 Refactor confirmation
  src/components/confirmation/Confirmation.tsx
  src/components/confirmation/ConfirmationModal.tsx
  src/components/confirmation/index.ts
  src/components/confirmation/useConfirmationModal.tsx
  src/components/custom-media-library/CustomMediaLibraryModal.tsx
  src/components/custom-media-library/DeleteConfirmationModal.tsx
  src/components/custom-media-library/LibraryUI.tsx
  src/components/custom-media-library/behavior.test.tsx
  src/components/custom-media-library/behavior.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
Labels: size/L

#631 Gallery modals UI
  src/components/confirmation/Confirmation.tsx
  src/components/confirmation/ConfirmationModal.tsx
  src/components/confirmation/useConfirmationModal.tsx
  src/components/custom-media-library/behavior.test.tsx
  src/components/custom-media-library/behavior.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
Labels: size/M

#632 DOP-1362 - Show errors uploading images
  src/abstractions/doppler-legacy-client/index.ts
  src/components/custom-media-library/CustomMediaLibraryModal.tsx
  src/components/custom-media-library/behavior.test.tsx
  src/components/custom-media-library/behavior.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/notification/Notification.tsx
  src/components/notification/NotificationModal.tsx
  src/components/notification/index.ts
  src/components/notification/useNotificationModal.tsx
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/dummies/doppler-legacy-client.tsx
  src/queries/image-gallery-queries.tsx
Labels: size/L

#634 DOP-1362 - Show errors
  src/components/custom-media-library/behavior.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/notification/Notification.tsx
  src/components/notification/NotificationModal.tsx
  src/components/notification/useNotificationModal.tsx
Labels: size/M

#635 Gallery message contents
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/notification/useNotificationModal.tsx
Labels: size/M
