Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2023-05, with the labels that each got.

#536 Bad test
  src/components/Campaign.test.tsx
  src/components/SaveAsTemplateModal.test.tsx
  src/components/SingletonEditor.test.tsx
Labels: size/S

#539 refactor: remove confusing abstraction EditorState
  src/abstractions/domain/editor.ts
  src/components/Campaign.test.tsx
  src/components/SingletonEditor.test.tsx
  src/components/SingletonEditor.tsx
  src/components/Template.test.tsx
  src/components/UnlayerEditorWrapper.test.tsx
  src/components/UnlayerEditorWrapper.tsx
Labels: size/L

#538 refactor: remove redundant event listener
  src/components/Campaign.test.tsx
  src/components/SingletonEditor.tsx
Labels: size/S

#543 Replace underscore by lodash
  package.json
  src/components/SingletonEditor.tsx
  yarn.lock
Labels: size/XS

#544 Editor state's refactoring - step 1/2
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/components/Main.tsx
  src/components/Template.test.tsx
  src/components/Template.tsx
  src/components/singleton-editor/SingletonEditorProvider.test.tsx
  src/components/singleton-editor/SingletonEditorProvider.tsx
  src/components/singleton-editor/index.ts
  src/components/singleton-editor/singletonDesignContext.ts
  src/components/singleton-editor/useSingletonEditor.ts
  src/utils/index.ts
Labels: size/L

#546 Editor state's refactoring - step 2/2
  src/components/Campaign.tsx
  src/components/Template.tsx
  src/components/singleton-editor/SingletonEditorProvider.test.tsx
  src/components/singleton-editor/reducer.test.ts
  src/components/singleton-editor/reducer.ts
  src/components/singleton-editor/useActionWhenNoPendingUpdates.test.tsx
  src/components/singleton-editor/useActionWhenNoPendingUpdates.ts
  src/components/singleton-editor/useContentUpdatesDetection.test.tsx
  src/components/singleton-editor/useContentUpdatesDetection.ts
  src/components/singleton-editor/useInitialContent.test.tsx
  src/components/singleton-editor/useInitialContent.ts
  src/components/singleton-editor/useSaving.test.tsx
  src/components/singleton-editor/useSaving.ts
  src/components/singleton-editor/useSingletonEditor.ts
  src/components/singleton-editor/useSingletonEditorState.test.tsx
  src/components/singleton-editor/useSingletonEditorState.ts
  src/components/singleton-editor/useUnloadWithPendingUpdatesPrevention.test.tsx
  src/components/singleton-editor/useUnloadWithPendingUpdatesPrevention.ts
Labels: size/XXL

#549 Minimal code refactorings
  src/components/Campaign.test.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/singleton-editor/useContentUpdatesDetection.ts
  src/components/singleton-editor/useSingletonEditorState.ts
Labels: size/M

#550 chore: improve noop types
  src/utils/index.ts
Labels: size/XS

#552 Add documentation links on Unlayer's types patches
  src/abstractions/domain/unlayer-type-patches.ts
Labels: size/S

#548 DE-990 - Save status
  src/abstractions/common/save-status.ts
  src/components/Campaign.tsx
  src/components/EditorTopBar.fakeTimer.test.tsx
  src/components/EditorTopBar.test.tsx
  src/components/EditorTopBar.tsx
  src/components/SaveIndicator.tsx
  src/components/Template.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/singleton-editor/useContentUpdatesDetection.test.tsx
  src/components/singleton-editor/useContentUpdatesDetection.ts
  src/components/singleton-editor/useSingletonEditor.ts
  src/components/singleton-editor/useSingletonEditorState.test.tsx
  src/components/singleton-editor/useSingletonEditorState.ts
Labels: size/L

#553 Gracefuly deal with saving errors
  src/components/singleton-editor/reducer.test.ts
  src/components/singleton-editor/reducer.ts
  src/components/singleton-editor/useSaving.test.tsx
  src/components/singleton-editor/useSaving.ts
  src/components/singleton-editor/useSingletonEditorState.test.tsx
  src/components/singleton-editor/useSingletonEditorState.ts
  src/utils/index.ts
Labels: size/XL

#551 DE-991 - Undo tools in header
  cspell-project-words.txt
  src/abstractions/domain/editor.ts
  src/abstractions/domain/unlayer-type-patches.ts
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/components/EditorTopBar.test.tsx
  src/components/EditorTopBar.tsx
  src/components/Template.tsx
  src/components/UndoTools.tsx
  src/components/UnlayerEditorWrapper.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/singleton-editor/index.ts
  src/components/singleton-editor/reducer.test.ts
  src/components/singleton-editor/reducer.ts
  src/components/singleton-editor/useContentUpdatesDetection.test.tsx
  src/components/singleton-editor/useContentUpdatesDetection.ts
  src/components/singleton-editor/useSingletonEditor.ts
  src/components/singleton-editor/useSingletonEditorState.test.tsx
  src/components/singleton-editor/useSingletonEditorState.ts
Labels: size/XL

#558 fix: add margin left
  src/components/Campaign.tsx
Labels: size/XS

#559 Change button as secondary
  src/components/Campaign.tsx
Labels: size/XS

#562 DE-992 - translate and sort field names
  cspell-project-words.txt
  src/components/UnlayerEditorWrapper.tsx
  src/components/i18n/en.tsx
  src/components/i18n/es.tsx
  src/components/useCustomFields.test.tsx
  src/components/useCustomFields.ts
  src/utils/index.test.ts
  src/utils/index.ts
Labels: size/XL

#566 Refactor modals as hooks
  package.json
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/components/SaveAsTemplateModal.tsx
  src/index.tsx
  yarn.lock
Labels: size/M

#569 No ticket small fixes related to the demo page
  README.md
  demo/index.html
  demo/start-demo.sh
Labels: size/XS

#568 DOP-1346 - MSEditor Gallery (Step 1/?)
  src/abstractions/domain/editor.ts
  src/components/Campaign.test.tsx
  src/components/Template.test.tsx
  src/components/custom-media-library/CustomMediaLibrary.tsx
  src/components/custom-media-library/CustomMediaLibraryModal.tsx
  src/components/custom-media-library/index.ts
  src/components/custom-media-library/useCustomMediaLibraryModal.test.tsx
  src/components/singleton-editor/SingletonEditorProvider.test.tsx
  src/components/singleton-editor/useCustomMediaLibrarySetup.test.tsx
  src/components/singleton-editor/useCustomMediaLibrarySetup.ts
  src/components/singleton-editor/useSingletonEditor.ts
Labels: size/L

#570 DOP-1346 - MSEditor Gallery (Step 2/?)
  cspell-project-words.txt
  src/components/custom-media-library/CustomMediaLibrary.tsx
  src/components/custom-media-library/CustomMediaLibraryModal.test.tsx
  src/components/custom-media-library/CustomMediaLibraryModal.tsx
  src/components/custom-media-library/Footer.test.tsx
  src/components/custom-media-library/Footer.tsx
  src/components/custom-media-library/Header.tsx
  src/components/custom-media-library/List.test.tsx
  src/components/custom-media-library/List.tsx
  src/components/custom-media-library/types.ts
  src/components/custom-media-library/useCustomMediaLibraryBehavior.test.tsx
  src/components/custom-media-library/useCustomMediaLibraryBehavior.tsx
  src/utils/index.test.ts
  src/utils/index.ts
Labels: size/XL

#577 DOP-1346 - MSEditor Gallery (Step 3/?)
  src/abstractions/domain/image-gallery.ts
  src/abstractions/doppler-legacy-client/index.ts
  src/abstractions/services.ts
  src/components/custom-media-library/CustomMediaLibrary.tsx
  src/components/custom-media-library/CustomMediaLibraryModal.test.tsx
  src/components/custom-media-library/List.tsx
  src/components/custom-media-library/types.ts
  src/components/custom-media-library/useCustomMediaLibraryBehavior.test.tsx
  src/components/custom-media-library/useCustomMediaLibraryBehavior.tsx
  src/composition-root.ts
  src/implementations/DopplerLegacyClientImpl.test.ts
  src/implementations/DopplerLegacyClientImpl.ts
  src/implementations/SingletonLazyAppServicesContainer.ts
  src/implementations/dummies/doppler-legacy-client.tsx
  src/queries/image-galleries-queries.tsx
Labels: size/L

#578 DOP-1346 - MSEditor Gallery (Step 4/?)
  src/components/custom-media-library/CustomMediaLibraryModal.tsx
  src/components/custom-media-library/Footer.tsx
  src/components/custom-media-library/Header.tsx
  src/components/custom-media-library/List.tsx
Labels: size/M
