Repository FromDoppler/doppler-editors-webapp, pull requests merged in 2023-03, with the labels that each got.

#438 Refactor Campaign Page tests
  src/components/Campaign.test.tsx
Labels: size/L

#439 Refactor Template Page tests
  src/components/Template.test.tsx
Labels: size/XL

#440 DE-960 - Smart save on exit
  src/components/Campaign.test.tsx
  src/components/Campaign.tsx
  src/components/SingletonEditor.test.tsx
  src/components/SingletonEditor.tsx
  src/components/Template.tsx
Labels: size/M

#441 DE-960 - Avoid redundant saving on exit when ato-save is in progress
  src/components/SingletonEditor.tsx
Labels: size/S

#457 DE-904 - Resolve unlayer editor manifest
  cspell-project-words.txt
  src/abstractions/asset-manifest-client/index.ts
  src/abstractions/configuration.ts
  src/abstractions/services.ts
  src/components/Campaign.test.tsx
  src/components/Editor.test.tsx
  src/components/Editor.tsx
  src/components/SingletonEditor.test.tsx
  src/components/Template.test.tsx
  src/composition-root.ts
  src/default-configuration.ts
  src/implementations/MfeLoaderAssetManifestClientImpl.test.ts
  src/implementations/MfeLoaderAssetManifestClientImpl.ts
  src/implementations/SingletonLazyAppServicesContainer.ts
  src/queries/unlayer-editor-extensions-entrypoints.tsx
Labels: size/L

#458 [DE-966] Show message when template is saving
  src/components/Template.tsx
Labels: size/XS

#466 DE-968 - inject css unlayer extensions
  src/abstractions/asset-manifest-client/index.ts
  src/components/Editor.test.tsx
  src/components/Editor.tsx
  src/implementations/MfeLoaderAssetManifestClientImpl.test.ts
  src/implementations/MfeLoaderAssetManifestClientImpl.ts
  src/queries/unlayer-editor-extensions-entrypoints.tsx
Labels: size/M

#467 Wait to save before navigating
  src/components/Campaign.tsx
  src/components/SingletonEditor.test.tsx
  src/components/SingletonEditor.tsx
  src/components/Template.tsx
Labels: size/S

#482 Update the UnlayerEditor interface
  public/index.html
  src/components/SingletonEditor.tsx
Labels: size/S
